url:
    group_url: http://127.0.0.1:5700/send_group_msg
    user_url: http://127.0.0.1:5700/send_private_msg
    recall_url: http://127.0.0.1:5700/delete_msg
    ban_url: http://127.0.0.1:5700/set_group_ban

fuck_reply: [
    '，艾特我干嘛? 有事儿说事儿，没事儿滚去日站!!!',
    '，别瞎鸡儿艾特我!!!',
    '，滚粗，白了否恩?!!',
    '，走开，嘤嘤嘤!!!',
    '，敲里吗，听见没有!!!',
    '，人家用小拳拳锤你胸口，哼!!!',
    '，艾特我干啥, 我在重构!!!',
    '，去去去，一边玩儿去，滚蛋!!!',
    '，葫芦娃，葫芦娃，一棵藤上七朵花!!!',
    '，干啥小崽子!!!',
    '，哪凉快哪待着!!!']

ban_word: [
    "ssr",
    "vpn",
    "porn",
    "黑产",
    "习近平",
    "酸酸乳",
    "gfw"]

usage_method: ['''
查询已知Poc：@我 showpoc system
查询已知Poc：@我 showpoc hardware
查询SSR: @我 py
查询SSR: @我 python
查询全部SSR: @我 allpy
查询全部SSR: @我 allpython
扫描子网工控设备：@我 protocols 111.200.232.0 1  --> 默认扫描子网 /24 返回第一页查询
扫描子网工控设备：@我 protocols 111.200.232.0 24 2  --> 扫描子网 /24 返回第二页查询
扫描子网工控设备：@我 protocols 111.200.232.0 16 1  --> 扫描子网段 /16 返回第一页查询
扫描子网工控设备：@我 protocols 111.200.232.77 TO 111.200.234.222 1  --> 扫描网段 返回第一页查询
查询天气：@我 北京市天气
查询天气：@我 朝阳区天气
查询天气：@我 Beijing天气
                        ''']

function_list: ['''
| 功能列表 |
--------------------------------------------------------------
找骂： 直接@ME
搜索论坛: @ME searchforum keyword
显示所有Poc：@ME showallpoc keyword(cms;hardware;industrial;system;information)
TCP端口扫描：@ME nmap host
CMS识别：@ME whatcms host
CMS漏洞扫描： @ME cms host
信息搜集: @ME information host
系统漏洞扫描： @ME system host
物联网设备安全检测: @ME hardware host
工控安全检测: @ME industrial host
搜索POC： @ME search keywords
搜索并使用POC进行安全检测： @ME search keywords host
神奇的梯子： @ME python(py)
子网工控设备扫描(返回页内容)： @ME protocols subnet sub_num(16/24) pge_num
查询天气： @ME ??市(区)天气
使用方法： @ME 食用
--------------------------------------------------------------
                        ''']
