url:
    group_url: http://127.0.0.1:5700/send_group_msg
    user_url: http://127.0.0.1:5700/send_private_msg
    recall_url: http://127.0.0.1:5700/delete_msg
    ban_url: http://127.0.0.1:5700/set_group_ban


fuck_reply: [
    '，艾特我干嘛? 有事儿说事儿，没事儿滚去日站!!!',
    '，别瞎鸡儿艾特我!!!',
    '，滚粗，白了否恩?!!',
    '，走开，嘤嘤嘤!!!',
    '，敲里吗，听见没有!!!',
    '，人家用小拳拳锤你胸口，哼!!!',
    '，艾特我干啥, 我在重构!!!',
    '，去去去，一边玩儿去，滚蛋!!!',
    '，葫芦娃，葫芦娃，一棵藤上七朵花!!!',
    '，干啥小崽子!!!',
    '，哪凉快哪待着!!!']
